Preparation for SPI (not working yet!)
git-svn-id: http://ategge1109/svn/openPOWERLINK_CNDK/trunk@51 0f5f4594-6328-11df-85c8-e91c4881b994

diff --git a/apps/EBV_DBC3C40_DigitalIO/create-this-app b/apps/EBV_DBC3C40_DigitalIO/create-this-app
--- a/apps/EBV_DBC3C40_DigitalIO/create-this-app
+++ b/apps/EBV_DBC3C40_DigitalIO/create-this-app
@@ -28,6 +28,7 @@ ${LIBAPIDIR}/utils"
 # Custom libraries
 LIBDIRS="${LIBAPIDIR}/target/nios2_newlib"
 LIBNAMES="CnApi"
+LIBTARGETFOLDER=$LIBAPIDIR/target/nios2_newlib
 
 ###############################################################################
 # Select here between debug and release settings
@@ -150,6 +151,25 @@ $cmd || {
     echo "nios2-app-generate-makefile failed"
     exit 1
 }
+
+echo
+echo "Rebuild target library before using it..."
+echo 
+make -C $LIBTARGETFOLDER clean
+make -C $LIBTARGETFOLDER
+
+if [ -f $LIBTARGETFOLDER/libCnApi.a ]
+then
+	echo
+	echo "Target library rebuild done!"
+	echo
+else
+    echo 
+    echo "Target library rebuild ERROR!"
+    echo "Rebuild stopped!"
+	echo
+    exit 1
+fi
 
 if [ -z "$SKIP_MAKE" ]; then
 	cmd="make"
