[FIX] A: determine instance ID automatically for make program-epcs

diff --git a/apps/ap_PDI/create-this-app b/apps/ap_PDI/create-this-app
--- a/apps/ap_PDI/create-this-app
+++ b/apps/ap_PDI/create-this-app
@@ -220,9 +220,39 @@ else
     exit 1
 fi
 
-cat >> Makefile <<'Heredoc'
+# get CPU instance number
+UART_INSTANCE_ID=
+#######################################
+# read UART_INSTANCE_ID of CPU_NAME
+# from JDI file
+#######################################
+CPU_NAME="ap_cpu"
+JDI_FILE=$SOPC_DIR/nios_openMac.jdi
+IN_FILE=$JDI_FILE
 
-# Rules for EPCS flash programming commands (EPCS contains SOF and application)
+if [ ! -f "$IN_FILE" ]
+then   # Exit if no such file.
+  echo "File $IN_FILE not found."
+  exit 1
+fi
+
+#check first if cpu name is present in file
+pattern=$CPU_NAME 
+
+match_count=$(grep -w -c "$pattern" ${IN_FILE})
+if [ $match_count -eq 0 ]; then
+    echo "match_count = ${match_count}"
+	echo "ERROR: File ${IN_FILE} does not contain pattern '${pattern}'"
+    exit 1
+fi
+
+# derive instance_id which corrensponds with CPU_NAME
+UART_INSTANCE_ID=$(grep -w "hpath" ${IN_FILE} | grep ${CPU_NAME} | awk '{split($0,a,"instance_id="); print a[2]}' | awk '{split($0,a,""); print a[2]}')
+echo "$CPU_NAME has INSTANCE: $UART_INSTANCE_ID"
+echo
+#######################################
+
+echo '# Rules for EPCS flash programming commands (EPCS contains SOF and application)
 PROGRAM_EPCS_SUFFIX := -epcs
 PROGRAM_EPCS_TARGET := $(addsuffix $(PROGRAM_EPCS_SUFFIX), $(FLASH_FILES))
 
@@ -234,17 +264,16 @@ SOF_FILE := $(wildcard $(QUARTUS_PROJECT_DIR)/*.sof)
 .PHONY : $(PROGRAM_EPCS_TARGET)
 $(PROGRAM_EPCS_TARGET) : $(ELF)
 
-	@$(ECHO) Info: Programming $(basename $@).flash	
+	@$(ECHO) Info: Programming $(basename $@).flash
 	@if [ -n "$($(basename $@)_EPCS_FLAGS)" ]; \
 	then \
 		nios2-configure-sof $(DOWNLOAD_CABLE_FLAG) -C $(QUARTUS_PROJECT_DIR); \
 		sof2flash --epcs --input=$(SOF_FILE) --output=sof.flash; \
 		$(ELF2FLASH) --after=sof.flash --input=$(ELF) --outfile=$(basename $@)_after_sof.flash --sim_optimize=$(SIM_OPTIMIZE) $(elf2flash_extra_args); \
 		$(ECHO) $(FLASHPROG) $(SOPC_SYSID_FLAG) --epcs --base=$($(basename $@)_START) sof.flash $(basename $@)_after_sof.flash; \
-		$(FLASHPROG) $(DOWNLOAD_CABLE_FLAG) $(SOPC_SYSID_FLAG) --epcs --base=$($(basename $@)_START) -g --override=../../powerlink/generic/nios2-flash-override.txt sof.flash $(basename $@)_after_sof.flash; \
-	fi
-
-Heredoc
+		$(FLASHPROG) $(DOWNLOAD_CABLE_FLAG) $(SOPC_SYSID_FLAG) --instance='$UART_INSTANCE_ID '--epcs --base=$($(basename $@)_START) \
+        -g --override=./target/altera_nios/nios2-flash-override.txt sof.flash $(basename $@)_after_sof.flash; \
+    fi' >> makefile
 
 if [ -z "$SKIP_MAKE" ]; then
 	cmd="make"
